<?php
/**
 * @see Netresearch_Epayments_Block_Info_HostedCheckout
 */

$label = $this->getPaymentProductLabel();
$info  = $this->getPaymentStatusInfo();
?>
<p>
    <?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
    <?php if ($label) echo ' - ',  $label ?>
    <?php if ($info): ?> 
        <br /><b><?php echo $this->__('Payment status:') ?></b><br />
        <?php echo $info ?>
    <?php endif ?>
</p>
